<?php
declare(strict_types=1);

const WGS_CONCEPT_DISCLOSURE = 'Independent concept created by Web Girl Studio to explore a realistic cultural-business challenge. The business, founder and scenario are fictional; the strategy, design direction and development are original WGS work.';

$projects = [
    'fortepiano-academy' => [
        'public' => true,
        'slug' => 'fortepiano-academy', 'name' => 'Fortepiano Academy', 'industry' => 'Education', 'status' => 'Client / Founder-built business / Live',
        'location' => 'Sydney, Australia', 'year' => '2026', 'order' => 0,
        'tags' => ['all', 'selected', 'client-work', 'business-services', 'education'],
        'starting' => 'A private teaching practice without a clear digital enrolment path',
        'transformation' => 'Turning a private teaching practice into a structured education brand, enrolment experience and digital system.',
        'caseTitle' => 'An education brand that makes serious teaching easier to understand and join.',
        'preview' => 'Fortepiano Academy needed to communicate rigorous music education without feeling cold or institutional. WGS shaped the positioning, identity, website and enquiry path into one clear system for families and adult students.',
        'proof' => 'A live education website with clear program routes, founder credibility, practical enrolment information and a direct enquiry flow.',
        'capabilities' => ['Strategy', 'Positioning', 'Identity', 'UX', 'Custom development'],
        'scope' => 'Strategy, positioning, information architecture, copy direction, visual identity, responsive design, custom development, enquiry flow, analytics and SEO foundations',
        'palette' => ['#111111', '#F4EFE6', '#C7BEB0', '#7B634D', '#E53B2F'],
        'media' => [
            'home-cover' => ['src' => '/img/fortepiano-academy-homepage.jpg', 'width' => 1440, 'height' => 1000, 'alt' => 'Fortepiano Academy live website homepage shown in a browser.', 'position' => 'center top'],
            'work-cover' => ['src' => '/img/fortepiano-academy-homepage.jpg', 'width' => 1440, 'height' => 1000, 'alt' => 'Fortepiano Academy live website homepage shown in a browser.', 'position' => 'center top'],
            'case-hero' => ['src' => '/img/fortepiano-academy-homepage.jpg', 'width' => 1440, 'height' => 1000, 'alt' => 'Fortepiano Academy live website homepage with program and enrolment messaging.', 'position' => 'center top'],
            'screen-desktop-01' => ['src' => '/img/fortepiano-academy-homepage.jpg', 'width' => 1440, 'height' => 1000, 'alt' => 'Desktop view of the Fortepiano Academy live website.', 'caption' => 'The opening establishes educational credibility and a clear route into programs and enrolment.', 'purpose' => 'Live homepage'],
        ],
        'seoTitle' => 'Fortepiano Academy Case Study | Web Girl Studio',
        'seoDescription' => 'How Web Girl Studio turned a private teaching practice into a structured education brand, live website and clearer enrolment experience.',
        'reality' => ['The teaching practice had depth, experience and a serious educational point of view, but prospective students and parents needed a clearer way to understand the programs, teaching approach and next step.', 'The website needed to hold artistic credibility and practical decision-making together: who the academy is for, what students can study, what the teaching feels like and how to enquire.'],
        'request' => 'Build a professional home for the academy and make enrolment easier to navigate.',
        'diagnosis' => 'This was not only a visual redesign. The practice needed a defined education brand, a useful program structure and a clear path from first impression to an informed enquiry.',
        'journeys' => [
            ['Parent or guardian', ['Search or referral', 'Understand the teaching standard', 'Compare programs', 'Check practical fit', 'Enquire']],
            ['Adult student', ['Discover the academy', 'See relevant study routes', 'Understand the approach', 'Ask about lessons']],
            ['Existing community', ['Return to the site', 'Find current information', 'Share a credible academy overview']],
        ],
        'insight' => 'The site needed to feel as considered as the teaching while answering practical enrolment questions in plain language.',
        'architecture' => ['Academy overview', 'Programs and pathways', 'Teaching approach', 'Founder credibility', 'Practical information', 'Enquiry flow'],
        'visual' => 'A restrained editorial system balances serious musical education with warmth. Strong typography, generous pacing and piano-derived graphic rhythm create character without obscuring the enrolment path.',
        'decisions' => [
            ['Programs are organised around student decisions.', 'Visitors can identify the relevant route before reading the full teaching philosophy.', 'Check whether a new visitor can find an appropriate program and enquiry action quickly.'],
            ['Credibility appears before the ask.', 'Teaching approach and founder experience support trust before the enquiry form.', 'Review the order with prospective students and parents.'],
            ['Mobile keeps the next step visible.', 'Program content and enquiry controls reflow without shrinking into desktop-like density.', 'Test at common phone widths and with keyboard navigation.'],
        ],
        'technical' => ['Responsive custom build with deliberate mobile hierarchy.', 'Semantic headings and metadata support SEO foundations.', 'Enquiry routes use clear labels and usable touch targets.', 'Analytics can measure visits and enquiry completion without collecting form values.'],
        'validation' => ['Verify all program and enquiry routes on mobile and desktop.', 'Check keyboard navigation, headings and focus states.', 'Confirm metadata, canonical URLs and analytics loading.', 'Track real outcomes only when sufficient live data is available.'],
        'proves' => 'Fortepiano Academy shows how WGS can turn founder expertise into a clear operating brand, a credible live website and a practical route into enquiry without flattening the character of the work.',
        'labStatus' => 'live-client', 'liveRoute' => 'https://fortepianoacademy.au', 'liveLabel' => 'Visit live site',
        'closeHeading' => 'Your expertise should be easier to understand and choose.',
        'closeBody' => 'WGS can turn a strong practice into a clear brand, website and enquiry system without sanding away what makes it distinctive.',
        'next' => 'mira-silt',
    ],
    'mira-silt' => [
        'public' => false,
        'slug' => 'mira-silt', 'name' => 'Mira Silt', 'industry' => 'Music', 'status' => 'Independent concept',
        'location' => 'Sydney, Australia', 'year' => '2026', 'order' => 1,
        'tags' => ['all', 'selected', 'culture', 'independent-concept', 'music-artists'],
        'starting' => 'Social and streaming presence without an owned digital world',
        'transformation' => 'The album already had a universe. The audience had nowhere to enter it.',
        'caseTitle' => 'An artist website that gives the whole album era one home.',
        'preview' => 'Mira’s music lived across streaming platforms, fragments of video and an exhausted link-in-bio. WGS shaped an owned release world for fans, press, promoters and future eras.',
        'proof' => 'An atmospheric artist platform with clear campaign states, listening, live dates, EPK access, merchandise and direct audience capture.',
        'capabilities' => ['Strategy', 'Art direction', 'UX', 'Artist platform', 'Campaign system'],
        'scope' => 'Strategy, audience journeys, information architecture, art direction, responsive web system, release campaign, EPK and measurement plan',
        'palette' => ['#090A0B', '#EEECE6', '#A8ABA9', '#4E345C', '#D82335'],
        'mediaCredit' => 'Creative direction and AI-generated concept imagery: Web Girl Studio.',
        'media' => [
            'home-cover' => [
                'src' => '/img/portfolio/mira-silt/cover-home-8x5.webp',
                'fallback' => '/img/portfolio/mira-silt/cover-home-8x5.jpg',
                'width' => 2400, 'height' => 1500,
                'alt' => 'Mira Silt seated in dark water among salt formations for the Salt Memory album era.',
                'position' => 'center center',
            ],
            'work-cover' => [
                'src' => '/img/portfolio/mira-silt/cover-work-4x3.webp',
                'mobileSrc' => '/img/portfolio/mira-silt/cover-work-mobile-4x5.webp',
                'width' => 1600, 'height' => 1200,
                'mobileWidth' => 1200, 'mobileHeight' => 1500,
                'alt' => 'Mira Silt in a mineral-black flooded studio with salt bloom and a red light signal.',
                'mobileAlt' => 'Vertical portrait of Mira Silt beside a salt-covered black surface.',
                'position' => 'left center',
                'mobilePosition' => 'center center',
            ],
            'case-hero' => [
                'src' => '/img/portfolio/mira-silt/case-hero-8x5.webp',
                'width' => 2880, 'height' => 1800,
                'alt' => 'Mira Silt in the dark-water visual world of her fictional debut album Salt Memory.',
                'position' => 'center center',
            ],
            'world-01' => [
                'src' => '/img/portfolio/mira-silt/world-01-16x9.webp',
                'width' => 2400, 'height' => 1350,
                'alt' => 'A black piano keyboard, translucent film and salt crystals partly submerged in dark water.',
                'caption' => 'Album-world material study: piano lacquer, translucent film, salt bloom and dark water.',
                'purpose' => 'Album world',
            ],
            'world-02' => [
                'src' => '/img/portfolio/mira-silt/world-02-live-16x9.webp',
                'width' => 2400, 'height' => 1350,
                'alt' => 'Mira Silt performing at a black grand piano on an intimate flooded stage.',
                'caption' => 'Live-performance direction designed to connect the album world to professional credibility.',
                'purpose' => 'Live world',
            ],
            'product-detail' => [
                'src' => '/img/portfolio/mira-silt/detail-01-product-square.webp',
                'width' => 1600, 'height' => 1600,
                'alt' => 'A blank oxidised-silver record sleeve, smoke-grey vinyl and salt-paper booklet on wet black lacquer.',
                'caption' => 'A limited physical edition extends the material system without inventing a live product.',
                'purpose' => 'Physical edition',
            ],
            'portrait-detail' => [
                'src' => '/img/portfolio/mira-silt/detail-02-portrait-square.webp',
                'width' => 1600, 'height' => 1600,
                'alt' => 'Close portrait of Mira Silt with damp black hair and an oxidised-silver ear cuff.',
                'caption' => 'Press portrait detail preserves the same fictional artist identity across the campaign system.',
                'purpose' => 'Press portrait',
            ],
            'press-portrait' => [
                'src' => '/img/portfolio/mira-silt/press-portrait-3x4.webp',
                'width' => 1800, 'height' => 2400,
                'alt' => 'Portrait of Mira Silt in black silk beside a salt-covered piano-black surface.',
                'caption' => 'Portrait-oriented media for EPK and editorial use.',
                'purpose' => 'EPK portrait',
            ],
            'og' => [
                'src' => '/img/portfolio/mira-silt/og-1200x630.jpg',
                'width' => 1200, 'height' => 630,
                'alt' => 'Mira Silt in the Salt Memory album world.',
            ],
            'screen-desktop-01' => ['src' => '/img/portfolio/mira-silt/screen-desktop-01-8x5.webp', 'width' => 2880, 'height' => 1800, 'alt' => 'Mira Silt interactive artist website opening in its release campaign state.', 'caption' => 'The release state puts the album, context and one listening action in the opening viewport.', 'purpose' => 'Release homepage'],
            'screen-desktop-02' => ['src' => '/img/portfolio/mira-silt/screen-desktop-02-8x5.webp', 'width' => 2880, 'height' => 1800, 'alt' => 'Mira Silt listening section with album information and an accessible preview player.', 'caption' => 'Album context, explicit playback and honest demo destinations share one practical release section.', 'purpose' => 'Listen system'],
            'screen-mobile-01' => ['src' => '/img/portfolio/mira-silt/screen-mobile-01.webp', 'width' => 780, 'height' => 1688, 'alt' => 'Mobile Mira Silt release homepage with current album action and campaign-state controls.', 'caption' => 'The mobile opening preserves the artist world while making the current action unmistakable.', 'purpose' => 'Mobile release state'],
            'screen-mobile-02' => ['src' => '/img/portfolio/mira-silt/screen-mobile-02.webp', 'width' => 780, 'height' => 1688, 'alt' => 'Mobile Mira Silt live-date section with clear fictional tour information.', 'caption' => 'Dates, cities and the demo ticket state remain readable without desktop compression.', 'purpose' => 'Mobile live dates'],
        ],
        'seoTitle' => 'Mira Silt - Music Website Concept | Web Girl Studio',
        'seoDescription' => 'A Web Girl Studio independent concept exploring how an album release becomes an owned world, campaign system, EPK and direct fan journey.',
        'reality' => ['Mira is a songwriter and keyboardist preparing her first full album after two independent EPs. Her audience discovers her through intimate rehearsal footage, cinematic fragments and platform recommendations. The attention is real; the context is not hers.', 'Streaming services are excellent listening destinations, but they place the artist inside someone else’s product. Social media creates discovery, then resets the story with every post. Promoters, press, collaborators and serious fans encounter different fragments and must assemble Mira for themselves.'],
        'request' => 'I need a website before the album announcement.',
        'diagnosis' => 'Mira does not need a more decorative collection of links. She needs control over context and a structure that survives the campaign. The album’s emotional language needs a durable home, while announce, pre-save, listen, buy, attend, cover, book and contact need a clear hierarchy.',
        'journeys' => [
            ['New listener', ['Reel or shared track', 'Current era', 'Hear or watch', 'Understand Mira’s voice', 'Listen or join']],
            ['Existing fan', ['Release news', 'Campaign state', 'Tickets or limited object', 'Exclusive fragment', 'Purchase or join']],
            ['Press, promoter or label', ['Referral or search', 'Artist context', 'Release and live proof', 'Current EPK', 'Professional contact']],
        ],
        'insight' => 'The site should be an era-based platform: a stable system whose skin, focal media and primary action can change as the artist moves from announcement to pre-save, release, tour and archive.',
        'architecture' => ['Current era / album landing', 'Listen and watch', 'Live dates', 'Transmissions / journal', 'Release archive', 'Shop', 'About', 'Press and EPK', 'Contact'],
        'visual' => 'Salt Memory is built from mineral black, oxidised silver, bruised violet and one severe red signal. Macro salt, skin, piano keys and dark water create intimacy without generic pop-star neon. Motion behaves like breath and damaged signal: slow displacement, interference and short flashes.',
        'decisions' => [
            ['Campaign action changes; the system does not.', 'The primary action moves through announcement, pre-save, listen, tickets and archive while navigation and content models remain stable.', 'Test whether visitors can identify the current campaign action within ten seconds.'],
            ['Audio supports discovery without taking control.', 'One deliberate preview uses explicit controls. Nothing starts with sound.', 'Verify keyboard, screen-reader and reduced-motion behaviour.'],
            ['EPK is a maintained product.', 'Biography, approved photos, credits, release information and contacts carry a visible revision date.', 'Ask a promoter to find the current EPK and correct contact.'],
        ],
        'technical' => ['One campaign action appears before atmospheric secondary media on mobile.', 'Audio controls retain a 44px minimum target and work without hover.', 'Credits reflow into labelled lists rather than horizontal tables.', 'Media is poster-led and does not preload full-screen video on mobile.', 'Reduced motion removes interference and parallax.'],
        'validation' => ['Identify the release and reach a listening destination within ten seconds.', 'Find the current EPK and professional contact without reopening navigation.', 'Confirm keyboard access for audio, gallery and menu controls.', 'Check image and video choices on average mobile connections.'],
        'proves' => 'Mira Silt shows how WGS protects an artist’s emotional language while building the practical infrastructure around it. It is a platform that can carry one era intensely, archive it properly and remain useful when the next era begins.',
        'lab' => 'The complete Mira Silt release platform will be the first culture project developed in WGS Lab.',
        'labStatus' => 'live',
        'labRoute' => '/projects/mira-silt/site/',
        'labLabel' => 'View the interactive artist website',
        'closeHeading' => 'Your release should have more than a link page.',
        'closeBody' => 'WGS can build the world around the work and the system behind the release - from fan journeys and campaign states to EPK, commerce and direct audience capture.',
        'next' => 'ninth-form',
    ],
    'ninth-form' => [
        'public' => false,
        'slug' => 'ninth-form', 'name' => 'Ninth Form', 'industry' => 'Fashion', 'status' => 'Independent concept',
        'location' => 'Sydney / Melbourne, Australia', 'year' => '2026', 'order' => 2,
        'tags' => ['all', 'selected', 'culture', 'independent-concept', 'fashion'],
        'starting' => 'Strong label identity trapped inside a generic ecommerce template',
        'transformation' => 'The garments had a point of view. The store reduced them to inventory.',
        'caseTitle' => 'A fashion store that protects the campaign and makes buying easier.',
        'preview' => 'Ninth Form’s campaigns attracted attention, but its storefront made an experimental label feel interchangeable. WGS joined editorial world-building to fit confidence, product clarity and wholesale access.',
        'proof' => 'A dual-mode fashion experience where campaign discovery and decisive commerce keep their own rhythm.',
        'capabilities' => ['Ecommerce strategy', 'Art direction', 'UX', 'Product system', 'Wholesale'],
        'scope' => 'Brand and commerce diagnosis, customer and buyer journeys, art direction, ecommerce UX, responsive product system, wholesale route and validation plan',
        'palette' => ['#EEE8DD', '#F8F5EE', '#161311', '#8B694B', '#175CFF'],
        'textColor' => '#161311',
        'mediaCredit' => 'Creative direction and AI-generated concept imagery: Web Girl Studio.',
        'media' => [
            'home-cover' => [
                'src' => '/img/portfolio/ninth-form/cover-home-8x5.webp',
                'fallback' => '/img/portfolio/ninth-form/cover-home-8x5.jpg',
                'width' => 2400, 'height' => 1500,
                'alt' => 'Ninth Form model wearing an asymmetric black, bone and tobacco modular look in a pattern-paper studio.',
                'position' => 'center center',
            ],
            'work-cover' => [
                'src' => '/img/portfolio/ninth-form/cover-work-4x3.webp',
                'mobileSrc' => '/img/portfolio/ninth-form/cover-work-mobile-4x5.webp',
                'width' => 1600, 'height' => 1200,
                'mobileWidth' => 1200, 'mobileHeight' => 1500,
                'alt' => 'Ninth Form model in sculptural black tailoring with layered construction and a functional blue fastening.',
                'mobileAlt' => 'Back view of the Ninth Form modular coat showing its asymmetric layers and blue fastening.',
                'position' => 'center center',
                'mobilePosition' => 'center center',
            ],
            'case-hero' => [
                'src' => '/img/portfolio/ninth-form/case-hero-8x5.webp',
                'width' => 2880, 'height' => 1800,
                'alt' => 'Ninth Form’s hero garment photographed against full-scale paper patterns.',
                'position' => 'center center',
            ],
            'world-01' => [
                'src' => '/img/portfolio/ninth-form/world-01-modular-16x9.webp',
                'width' => 2400, 'height' => 1350,
                'alt' => 'The Ninth Form hero look reconfigured with its bone underlayer, black outer coat and detachable tobacco panel.',
                'caption' => 'A second configuration proves that modularity is part of the garment system, not styling theatre.',
                'purpose' => 'Modular world',
            ],
            'world-02' => [
                'src' => '/img/portfolio/ninth-form/world-02-workroom-16x9.webp',
                'width' => 2400, 'height' => 1350,
                'alt' => 'A Ninth Form worktable with paper pattern, black wool, bone cotton, blue webbing and a half-assembled tailored shoulder.',
                'caption' => 'Pattern cutting, material authorship and construction become part of the evidence behind the collection.',
                'purpose' => 'Workroom',
            ],
            'product-detail' => [
                'src' => '/img/portfolio/ninth-form/detail-01-components-square.webp',
                'width' => 1600, 'height' => 1600,
                'alt' => 'The four components of a Ninth Form look: black coat, bone underlayer, tobacco panel and blue strap.',
                'caption' => 'The four components clarify what belongs to the complete hero look.',
                'purpose' => 'Modular components',
            ],
            'portrait-detail' => [
                'src' => '/img/portfolio/ninth-form/detail-02-construction-square.webp',
                'width' => 1600, 'height' => 1600,
                'alt' => 'Close view of Ninth Form wool, cotton, tailoring canvas, detachable tabs and blue steel fastening.',
                'caption' => 'Fabric, internal construction and detachable hardware support more specific product information.',
                'purpose' => 'Construction detail',
            ],
            'press-portrait' => [
                'src' => '/img/portfolio/ninth-form/wholesale-portrait-3x4.webp',
                'width' => 1800, 'height' => 2400,
                'alt' => 'A compact Ninth Form capsule on a garment rail with blank line sheets, fabric swatches and hardware.',
                'caption' => 'A coherent capsule and blank professional materials establish the wholesale route without inventing stockists.',
                'purpose' => 'Wholesale capsule',
            ],
            'og' => [
                'src' => '/img/portfolio/ninth-form/og-1200x630.jpg',
                'width' => 1200, 'height' => 630,
                'alt' => 'Ninth Form asymmetric tailoring campaign.',
            ],
            'screen-desktop-01' => ['src' => '/img/portfolio/ninth-form/screen-desktop-01-8x5.webp', 'width' => 2880, 'height' => 1800, 'alt' => 'Ninth Form World-mode campaign homepage with a route into the capsule.', 'caption' => 'World mode builds desire and keeps the path into the product system visible.', 'purpose' => 'Campaign homepage'],
            'screen-desktop-02' => ['src' => '/img/portfolio/ninth-form/screen-desktop-02-8x5.webp', 'width' => 2880, 'height' => 1800, 'alt' => 'Ninth Form Shop-mode product page showing garment, price, availability, sizing and action.', 'caption' => 'Shop mode answers the buying questions without removing the collection’s visual point of view.', 'purpose' => 'Product system'],
            'screen-mobile-01' => ['src' => '/img/portfolio/ninth-form/screen-mobile-01.webp', 'width' => 780, 'height' => 1688, 'alt' => 'Mobile Ninth Form campaign opening using a dedicated portrait composition.', 'caption' => 'The mobile campaign uses its own art direction rather than cropping the desktop hero.', 'purpose' => 'Mobile campaign'],
            'screen-mobile-02' => ['src' => '/img/portfolio/ninth-form/screen-mobile-02.webp', 'width' => 780, 'height' => 1688, 'alt' => 'Mobile Ninth Form product view with garment, price, availability, fit guide, sizes and add-to-bag action.', 'caption' => 'The mobile product state puts price, availability, fit, size and action before extended editorial copy.', 'purpose' => 'Mobile product state'],
        ],
        'seoTitle' => 'Ninth Form - Fashion Ecommerce Concept | Web Girl Studio',
        'seoDescription' => 'A Web Girl Studio independent concept joining editorial fashion art direction to fit clarity, product confidence and wholesale systems.',
        'reality' => ['Founded by fictional pattern cutter Eden Vale, Ninth Form creates small seasonal capsules built from asymmetric tailoring and modular garments. The label already has recognisable imagery and a clear point of view.', 'Its store does not carry that intelligence. Products appear as isolated thumbnails, fit questions arrive in messages and wholesale interest disappears into manually updated PDFs. The visual world attracts attention; the operational layer makes buying harder than it needs to be.'],
        'request' => 'We need a more custom Shopify site.',
        'diagnosis' => 'The existing store separates desire from confidence. Campaign imagery sells the silhouette, then the product page asks the customer to infer fit, fabric behaviour, scale and styling from minimal information. Customers need precision; buyers need current collection data; press and stylists need approved imagery and credits.',
        'journeys' => [
            ['Returning customer', ['Collection release', 'Current capsule', 'Intelligent filter', 'Fit and material', 'Confident purchase']],
            ['New visitor', ['Campaign story', 'Label point of view', 'Collection', 'Size and availability', 'Purchase or save']],
            ['Buyer, stylist or press', ['Collections', 'Stockist context', 'Line sheet or assets', 'Professional route']],
        ],
        'insight' => 'Fashion does not have to choose between editorial authorship and usable commerce. World creates desire and context; Shop answers practical questions quickly and honestly. Each mode leads to the other without confusing their jobs.',
        'architecture' => ['Current campaign', 'Shop all', 'Collection stories', 'Product details', 'Journal / process', 'About and production', 'Stockists', 'Press', 'Wholesale', 'Customer care'],
        'visual' => 'Warm paper, bone, ink, faded tobacco and electric-blue annotation create a fashion language that feels worked on rather than polished into anonymity. Full bodies and garment details share space with pattern-cutting marks, measurements and controlled negative space.',
        'decisions' => [
            ['Campaign images connect to exact looks.', 'An unobtrusive look index reveals garments and styling relationships while the image remains an image first.', 'Test the campaign-to-product path and return context.'],
            ['Fit becomes authored content.', 'Model measurements, worn size, garment measurements, fit, fabric behaviour and construction follow one hierarchy.', 'Ask first-time users to explain fit and choose a size.'],
            ['Professional access stays separate.', 'Wholesale and press remain findable without interrupting the consumer journey.', 'Test whether buyers reach the current line sheet without entering the shop flow.'],
        ],
        'technical' => ['Mobile campaign imagery uses intentional 4:5 or 3:4 crops.', 'Product details put price, availability, fit and action before long editorial content.', 'Measurement tables become labelled rows at 320px.', 'Product media loads progressively below the purchase controls.', 'No effect delays size selection, price or Add to Bag.'],
        'validation' => ['Move from campaign look to exact product and back without losing context.', 'Select a size using only product-page fit information.', 'Find the current wholesale route.', 'Verify gallery and size controls by keyboard.'],
        'proves' => 'Ninth Form proves that WGS can treat art direction and commerce as one system without confusing their jobs. Desire opens the door; fit, material, production and delivery create confidence.',
        'lab' => 'The Lab edition will prototype the campaign-to-product journey and responsive fit system after Mira Silt.',
        'labStatus' => 'live',
        'labRoute' => '/projects/ninth-form/site/',
        'labLabel' => 'View the interactive fashion store',
        'closeHeading' => 'Your store should not erase the point of view that brought people there.',
        'closeBody' => 'WGS creates editorial commerce systems where image, product information, fit and operational pathways reinforce one another.',
        'next' => 'second-weather',
    ],
    'second-weather' => [
        'slug' => 'second-weather', 'name' => 'Second Weather Films', 'industry' => 'Cinema and production', 'status' => 'Independent concept',
        'location' => 'Australia', 'year' => '2026', 'order' => 3,
        'tags' => ['all', 'culture', 'independent-concept', 'screen', 'film-media'],
        'starting' => 'Strong work scattered across video platforms, decks and personal profiles',
        'transformation' => 'The films were winning attention one by one. The company behind them remained invisible.',
        'preview' => 'Second Weather had finished films, commissioned work and a feature in development, but no coherent slate. WGS created a cinematic company presence for audiences, commissioners, collaborators and private project conversations.',
        'proof' => 'A film system with public work, accurate credits, commissioner routing and controlled project access.',
        'capabilities' => ['Film portfolio', 'Content architecture', 'UX', 'Video performance', 'Professional workflows'],
        'scope' => 'Company positioning, audience and commissioner journeys, slate architecture, cinematic art direction, film records, controlled project access and validation plan',
        'palette' => ['#050607', '#F1EFE8', '#293845', '#D58A38', '#8E9296'],
        'seoTitle' => 'Second Weather Films - Production Website Concept | Web Girl Studio',
        'seoDescription' => 'A Web Girl Studio independent concept turning scattered films and decks into a cinematic slate, press system and commissioner journey.',
        'reality' => ['Second Weather is a fictional independent production company working across narrative film, music video and commissioned culture. Finished work attracts attention, but the company story is fragmented across video platforms, individual profiles and pitch decks.', 'A viewer can appreciate one film without understanding the creative partnership, range of the slate or path to commission new work. Projects in development need controlled context rather than public thumbnails or insecure links.'],
        'request' => 'We need a more cinematic showreel site.',
        'diagnosis' => 'The problem is not a lack of moving image. It is a lack of company-level structure. Films need accurate records and credits; commissioners need a concise route into capability; collaborators need context; sensitive projects need genuine access control.',
        'journeys' => [
            ['Audience or press', ['Film referral', 'Watch', 'Credits and context', 'Related work', 'Company understanding']],
            ['Commissioner', ['Capability referral', 'Selected slate', 'Relevant work', 'Production approach', 'Enquiry']],
            ['Collaborator or partner', ['Project or person', 'Role and credits', 'Company slate', 'Contact']],
        ],
        'insight' => 'The site should behave like a slate, not a showreel: every film remains a complete record while the relationships between works make the production company visible.',
        'architecture' => ['Selected slate', 'Film records', 'Commissioned work', 'In development', 'Company', 'People and collaborators', 'News / screenings', 'Press resources', 'Commissioner enquiry', 'Controlled project room'],
        'visual' => 'Cinema black, warm subtitle white, sodium amber and storm blue frame the work without pretending to be the work. Timecode, production documents and edge markings become precise proof objects rather than decorative film-strip clichés.',
        'decisions' => [
            ['The slate leads; the showreel supports.', 'Visitors can understand range and individual works without committing to a forced montage.', 'Test whether commissioners can identify relevant capability without watching a full reel.'],
            ['Every film is a durable record.', 'Credits, synopsis, format, availability and related work remain attached to the film.', 'Audit credit completeness across sample records.'],
            ['Private rooms use real access states.', 'Development materials are described clearly and protected in a real build.', 'Validate access, expiry and error states before activation.'],
        ],
        'technical' => ['Video is poster-led and never autoplays with sound.', 'Captions and transcript readiness are part of the media model.', 'Mobile prioritises title, still, role and one action.', 'Credits reflow into semantic groups.', 'Private-room controls remain disabled until a real authenticated build exists.'],
        'validation' => ['Find the right film and complete credits from a referral.', 'Identify the company’s capability from the slate.', 'Reach a commissioner enquiry without passing through a generic contact form.', 'Test captions, keyboard media control and mobile page weight.'],
        'proves' => 'Second Weather shows that WGS can turn moving-image work into a coherent company system: cinematic in presentation, exact in credits and practical for the people who commission, cover and collaborate.',
        'lab' => 'The Lab edition will prototype a public slate, one complete film record and a clearly labelled private-room state.',
        'closeHeading' => 'A reel can show the work. A slate can reveal the company behind it.',
        'closeBody' => 'WGS builds film and production platforms that balance cinematic attention with credits, professional routes and controlled project context.',
        'next' => 'quiet-signal',
    ],
    'sasha-mirev' => [
        'slug' => 'sasha-mirev', 'name' => 'Sasha Mirev', 'industry' => 'Contemporary art', 'status' => 'Independent concept',
        'location' => 'Sydney / Naarm-Melbourne', 'year' => '2026', 'order' => 4,
        'tags' => ['all', 'culture', 'independent-concept', 'art', 'art-archives'],
        'starting' => 'Instagram presence and PDFs without a usable archive',
        'transformation' => 'A decade of work existed. The archive did not.',
        'preview' => 'Sasha’s installations moved between material, memory and migration. Curators encountered them as isolated posts and expired PDFs. WGS designed a living archive that preserves context while remaining usable to institutions, writers and collectors.',
        'proof' => 'A relational artwork system joining slow looking to precise metadata, rights, documents and enquiry routes.',
        'capabilities' => ['Digital archive', 'Content model', 'Art direction', 'Accessibility', 'Institutional UX'],
        'scope' => 'Archive diagnosis, curator, researcher and collector journeys, relational content model, responsive archive interface, rights and credit system, validation plan',
        'palette' => ['#F4F2EC', '#626560', '#617569', '#B93A2E', '#111211'],
        'seoTitle' => 'Sasha Mirev - Artist Archive Concept | Web Girl Studio',
        'seoDescription' => 'A Web Girl Studio independent concept turning a fragmented art practice into a relational archive for curators, writers and collectors.',
        'reality' => ['Sasha’s fictional interdisciplinary practice spans installation, sculpture, sound and photographic documents. The body of work matters as a network: objects appear in installations, exhibitions produce texts and photographic records preserve temporary work.', 'The current materials do not preserve that network. Curators repeatedly request the same files, credits vary and older work overwhelms the current PDF while current work lacks space.'],
        'request' => 'I need a cleaner artist portfolio.',
        'diagnosis' => 'A cleaner grid would preserve the confusion. The website must distinguish artwork from series, installation view from work record and exhibition from either. It needs slow looking alongside precise metadata, rights, documents and discreet professional enquiries.',
        'journeys' => [
            ['Curator or institution', ['Referral', 'Current practice', 'Relevant series', 'Exhibition history', 'Resources and enquiry']],
            ['Writer or researcher', ['Work or exhibition', 'Connected text', 'Documentation', 'Citation and credit']],
            ['Collector or adviser', ['Selected works', 'Scale and material', 'Context', 'Availability enquiry']],
            ['General audience', ['Image-led entry', 'Body of work', 'Relationships', 'Deeper context']],
        ],
        'insight' => 'The archive should be relational, not a chronological dumping ground. The interface can remain quiet because the content model carries the complexity.',
        'architecture' => ['Current work', 'Works by series', 'Exhibitions', 'Texts and conversations', 'About the practice', 'CV', 'News', 'Press resources', 'Enquiries'],
        'visual' => 'Gallery white without gallery sterility: mineral grey, oxidised green and restrained vermilion. The artwork determines each media ratio. Typography is archival and contemporary; motion is almost invisible and never performs over the work.',
        'decisions' => [
            ['Artwork proportions remain evidence.', 'Variable-ratio media and stable captions replace forced identical crops.', 'Review every sample work at desktop and mobile ratios.'],
            ['Works, series and exhibitions are different entities.', 'Labels, breadcrumbs and relationships make the archive legible without turning it into database theatre.', 'Test whether users can explain each relationship.'],
            ['Downloads are approved and current.', 'CV, biography and press images carry dates, versions and credit requirements.', 'Ask a curator to retrieve one approved image and the current CV.'],
        ],
        'technical' => ['Mobile preserves artwork ratios and keeps captions with images.', 'Metadata uses labelled definition lists rather than wide tables.', 'High-resolution press downloads remain separate from page images.', 'Rights and photographer credits stay attached to every use.', 'Relationships are modelled once rather than duplicated across records.'],
        'validation' => ['Audit metadata completeness across the sample archive.', 'Retrieve the current CV and one approved image.', 'Distinguish work, series and exhibition.', 'Validate alternative text, captions and rights credits.'],
        'proves' => 'Sasha Mirev proves that WGS can treat an artist’s body of work as culture and information at the same time. The visual quiet is made possible by a precise archive underneath it.',
        'lab' => 'The Lab edition will model one series, one exhibition, connected works, a current CV and professional resource access.',
        'closeHeading' => 'A body of work deserves more than a grid.',
        'closeBody' => 'WGS designs cultural archives that protect the experience of the work while making records, relationships and professional materials genuinely usable.',
        'next' => 'mira-silt',
    ],
    'quiet-signal' => [
        'slug' => 'quiet-signal', 'name' => 'Quiet Signal', 'industry' => 'Independent media', 'status' => 'Independent concept',
        'location' => 'Australia / Asia-Pacific', 'year' => '2026', 'order' => 5,
        'tags' => ['all', 'culture', 'independent-concept', 'media', 'film-media'],
        'starting' => 'Social-first publication with a growing audience and unusable archive',
        'transformation' => 'The publication had an audience. It did not yet have an institution.',
        'preview' => 'Quiet Signal’s essays, interviews and short films travelled widely on social, then disappeared into the feed. WGS designed an editorial home built for discovery, recurring readership, contributors and serious cultural partnerships.',
        'proof' => 'A publishing system where stories accumulate through subjects, people, formats and series rather than vanish after one post.',
        'capabilities' => ['Editorial platform', 'CMS architecture', 'UX', 'Technical SEO', 'Partnership funnel'],
        'scope' => 'Publication positioning, reader, contributor and partner journeys, taxonomy, CMS content model, visual system, article experience, technical SEO and measurement plan',
        'palette' => ['#F4F0E8', '#0A0A0A', '#1748C8', '#FF7855', '#C9C5BC'],
        'seoTitle' => 'Quiet Signal - Editorial Platform Concept | Web Girl Studio',
        'seoDescription' => 'A Web Girl Studio independent concept building a social-first culture publication into a discoverable editorial institution.',
        'reality' => ['Quiet Signal is a fictional publication covering emerging music, fashion image-making, film and internet culture across Australia and the Asia-Pacific.', 'Its audience primarily arrives through social posts. Full pieces live in a weakly categorised newsletter archive, contributor credits vary and commercial enquiries arrive beside editorial pitches.'],
        'request' => 'We have outgrown Substack and need a proper magazine site.',
        'diagnosis' => 'Changing platform is the visible event; becoming an institution is the real transition. That requires editorial taxonomy, authorship, rights and credits, newsletter relationships, partnership boundaries, corrections, media handling and a repeatable publishing workflow.',
        'journeys' => [
            ['Social visitor', ['Specific story', 'Full experience', 'Related subject or person', 'Subscribe or continue']],
            ['Loyal reader', ['Homepage or newsletter', 'Lead stories', 'Beat, author or series', 'Return']],
            ['Contributor', ['Editorial scope', 'Standards', 'Structured pitch']],
            ['Partner or sponsor', ['Principles', 'Partnership formats', 'Commercial enquiry']],
        ],
        'insight' => 'The platform should be organised for accumulation and return, not only recency. Subjects, people, formats, contributors and named series create multiple meaningful ways back into one canonical story.',
        'architecture' => ['Current issue', 'Music', 'Fashion', 'Screen', 'Art and image', 'Internet culture', 'Watch / listen', 'Series', 'Contributors', 'Newsletter', 'Editorial principles', 'Pitch us', 'Partnerships'],
        'visual' => 'Newsprint white, signal black, cobalt and fluorescent apricot create a publication that feels alive without becoming a chaotic moodboard. A modular typographic system supports long reading, dense credits, photo essays, video and audio.',
        'decisions' => [
            ['Every story has complete authorship.', 'Credits adapt by format without collapsing every role into an ambiguous byline.', 'Audit role and rights completeness across sample stories.'],
            ['Discovery is relational.', 'Stories connect through subject, format, person, series and contributor rather than chronology alone.', 'Test retrieval of an older interview by three routes.'],
            ['Editorial and commercial contact remain separate.', 'Pitch guidance and partnership formats protect both efficiency and editorial trust.', 'Test which route contributors and partners choose.'],
        ],
        'technical' => ['Article text holds comfortable line lengths and heading rhythm.', 'Photo essays preserve intentional sequence and ratio.', 'Audio and video are caption and transcript ready.', 'Canonical URLs, metadata, sitemaps and pagination are product requirements.', 'Corrections and update dates remain visible and machine-readable.'],
        'validation' => ['Continue from a social landing into a second relevant story.', 'Find an older interview by person, subject or series.', 'Validate reading comfort, heading structure and metadata.', 'Test contributor versus partnership route selection.'],
        'proves' => 'Quiet Signal proves that WGS can design an editorial institution, not merely a magazine surface. The visual identity gives it a voice; the content model lets stories accumulate cultural value.',
        'lab' => 'The Lab edition will prototype a current-issue homepage, one long-form story, one contributor or subject route and separate pitch and partnership paths.',
        'closeHeading' => 'Publishing needs somewhere for attention to become an archive.',
        'closeBody' => 'WGS builds editorial platforms where identity, reading, discovery, authorship and commercial sustainability remain part of one coherent system.',
        'next' => 'sasha-mirev',
    ],
];

// Non-public pipeline data. Empty fields are deliberate and must be replaced
// with approved content and real evidence before this case study is published.
$caseStudyPipeline = [
    'face-not-fake' => [
        'visibility' => 'draft', 'client' => 'Face Not Fake', 'industry' => 'Wellness',
        'problem' => '', 'strategy' => '', 'positioning' => '',
        'offerArchitecture' => [], 'informationArchitecture' => [],
        'visualDirection' => '', 'development' => '', 'bookingIntegration' => '',
        'seoFoundation' => '', 'beforeAfter' => [], 'realOutcomes' => [], 'testimonial' => null,
    ],
];

// Reusable testimonial data. Placeholder records are never rendered publicly.
$testimonials = [
    'fortepiano-academy' => [
        'status' => 'placeholder', 'quote' => 'Approved client testimonial to be added here.',
        'name' => 'Client name pending approval', 'business' => 'Fortepiano Academy',
    ],
];

$filterLabels = [
    'all' => 'All projects',
    'music-artists' => 'Music & artists',
    'fashion' => 'Fashion',
    'film-media' => 'Film & media',
    'art-archives' => 'Art & archives',
    'business-services' => 'Business & services',
];

function wgs_project_url(string $slug): string
{
    return '/projects/' . rawurlencode($slug) . '/';
}
