<?php declare(strict_types=1); http_response_code(404); exit('Project not found'); require dirname(__DIR__, 3) . '/components/portfolio.php'; require dirname(__DIR__, 3) . '/components/analytics.php'; ?>
<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Mira Silt — Interactive Artist Website | WGS Lab</title>
<meta name="description" content="A fictional interactive album and artist website created by Web Girl Studio.">
<meta name="robots" content="noindex, follow"><link rel="canonical" href="https://webgirl.studio/projects/mira-silt/site/">
<meta property="og:image" content="https://webgirl.studio/img/portfolio/mira-silt/og-1200x630.jpg">
<?php wgs_analytics_head(); ?>
<link rel="icon" href="<?= portfolio_asset('assets/favicon.svg') ?>" type="image/svg+xml">
<link rel="stylesheet" href="<?= portfolio_asset('assets/culture-lab.css') ?>"><script defer src="<?= portfolio_asset('assets/culture-lab.js') ?>"></script>
</head><body class="lab-body mira-site" data-lab-site="mira">
<a class="lab-skip" href="#lab-main">Skip to content</a>
<div class="concept-strip"><a href="/projects/mira-silt/">← Mira Silt case study</a><span>Independent fictional concept · not an operating business</span></div>
<header class="mira-nav"><a href="#top" class="mira-wordmark">MIRA SILT</a><nav data-lab-menu aria-label="Mira Silt navigation"><a href="#listen">Listen</a><a href="#live">Live</a><a href="#objects">Editions</a><a href="#about">About</a><button type="button" data-open-dialog="mira-epk">Press / EPK</button></nav><button class="mira-menu" type="button" data-menu-toggle aria-expanded="false">Menu</button></header>
<main id="lab-main">
<section class="mira-hero" id="top"><img src="/img/portfolio/mira-silt/case-hero-8x5.webp" alt="Mira Silt seated in dark water among salt formations" width="2880" height="1800" fetchpriority="high"><div class="mira-hero-shade"></div><div class="mira-hero-copy"><p data-era-date>The debut album · Out now</p><h1 data-era-label>Salt Memory</h1><span data-era-note>Nine songs about what the body remembers after the story changes.</span><a href="#listen" data-era-link><span data-era-action>Listen to the album</span> <b aria-hidden="true">↘</b></a></div><div class="era-switch" aria-label="Preview campaign state"><span>Campaign state</span><button type="button" data-era="announce">Announce</button><button type="button" class="active" data-era="release">Release</button><button type="button" data-era="tour">Tour</button></div></section>
<section class="mira-listen" id="listen"><div class="section-number">01 / Listen</div><div class="listen-copy"><p>Current release</p><h2>Salt Memory</h2><p class="plain">Nine songs built from close piano, restrained vocals and electronics that slowly lose their shape.</p></div><div><div class="player"><button class="play" type="button" data-player aria-label="Play album preview">▶</button><div class="track"><p><b>02</b> What the Water Kept</p><div class="progress"><i data-progress></i></div></div><time data-player-time>0:28 / 3:18</time></div><div class="platforms"><span>Demo listening destinations</span><button type="button" data-demo-status="Bandcamp link is a demo">Bandcamp ↗</button><button type="button" data-demo-status="Spotify link is a demo">Spotify ↗</button><button type="button" data-demo-status="Apple Music link is a demo">Apple Music ↗</button></div></div></section>
<section class="mira-film"><img src="/img/portfolio/mira-silt/world-01-16x9.webp" alt="Piano keys, salt crystals and translucent film submerged in dark water" width="2400" height="1350" loading="lazy"><button type="button" data-video-demo><span>Watch demo</span> What the Water Kept <b>03:41</b></button></section>
<section class="mira-live" id="live"><div class="section-number">02 / Live</div><div class="live-intro"><h2>Salt Memory,<br>in the room.</h2><p>Piano, electronics and a four-piece ensemble. These fictional dates demonstrate the tour-information system.</p></div><div class="show-list"><?php foreach ([['03 OCT','Sydney, NSW','Demo venue'],['09 OCT','Newcastle, NSW','Demo venue'],['16 OCT','Melbourne, VIC','Demo venue'],['22 OCT','Brisbane, QLD','Demo venue']] as [$date,$city,$venue]): ?><button type="button" data-demo-status="Ticketing is disabled in this concept"><time><?= e($date) ?></time><span><?= e($city) ?><small><?= e($venue) ?></small></span><b>Demo tickets ↗</b></button><?php endforeach; ?></div><img src="/img/portfolio/mira-silt/world-02-live-16x9.webp" alt="Mira Silt performing at a grand piano on an intimate flooded stage" width="2400" height="1350" loading="lazy"></section>
<section class="mira-objects" id="objects"><div class="object-image"><img src="/img/portfolio/mira-silt/detail-01-product-square.webp" alt="Salt Memory vinyl and lyric booklet concept" width="1600" height="1600" loading="lazy"><span>Concept edition</span></div><div class="object-copy"><div class="section-number">03 / Physical edition</div><h2>Salt Memory<br>on smoke-grey vinyl.</h2><p>A fictional hand-numbered record, salt-paper lyric booklet and one unreleased piano piece.</p><div class="object-buy"><span>$48 AUD · Demo</span><button type="button" data-demo-status="Bag interactions are disabled in this artist concept">Preview only</button></div></div></section>
<section class="mira-about" id="about"><img src="/img/portfolio/mira-silt/press-portrait-3x4.webp" alt="Portrait of fictional artist Mira Silt" width="1800" height="2400" loading="lazy"><div><div class="section-number">04 / About</div><h2>Close piano.<br>Damaged signal.<br>A voice kept low.</h2><p>Mira Silt is a fictional Sydney songwriter and keyboardist created to demonstrate a complete artist platform.</p><button type="button" data-open-dialog="mira-epk">Open press kit →</button></div></section>
<section class="transmission"><p>Studio notes, first access to songs and live dates before social.</p><form data-demo-form><label for="mira-email">A quiet transmission</label><div><input id="mira-email" type="email" required placeholder="Email address"><button>Join demo →</button></div><small>No information is submitted or stored.</small></form></section>
</main><footer class="mira-footer"><span>MIRA SILT</span><div><a href="/projects/mira-silt/">Read the WGS case study</a><button type="button" data-open-dialog="mira-epk">Press / EPK</button></div><p>Independent fictional concept by Web Girl Studio · not an operating artist · 2026</p></footer>
<div class="lab-status" aria-live="polite" data-lab-status></div>
<div class="mira-modal" id="mira-epk" data-dialog role="dialog" aria-modal="true" aria-labelledby="mira-epk-title" hidden><button class="modal-close" type="button" data-close-dialog>Close ×</button><p>Press / EPK · Concept edition</p><h2 id="mira-epk-title">Everything you need,<br>in one place.</h2><div class="epk-grid"><img src="/img/portfolio/mira-silt/detail-02-portrait-square.webp" alt="Mira Silt press portrait" width="1600" height="1600"><div><h3>Mira Silt</h3><p>Fictional Sydney alternative-pop artist, songwriter and keyboardist. This EPK demonstrates maintained biography, imagery, credits and professional routing.</p><button type="button" data-demo-status="Biography download is a demo">Short biography ↓</button><button type="button" data-demo-status="Image download is a demo">Approved images ↓</button><button type="button" data-demo-status="Credits download is a demo">Release credits ↓</button></div></div></div>
</body></html>
