<?php declare(strict_types=1); http_response_code(404); exit('Project not found'); require dirname(__DIR__, 3) . '/components/portfolio.php'; require dirname(__DIR__, 3) . '/components/analytics.php'; ?>
<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Ninth Form — Interactive Fashion Store | WGS Lab</title><meta name="description" content="A fictional interactive editorial fashion store created by Web Girl Studio.">
<meta name="robots" content="noindex, follow"><link rel="canonical" href="https://webgirl.studio/projects/ninth-form/site/"><meta property="og:image" content="https://webgirl.studio/img/portfolio/ninth-form/og-1200x630.jpg">
<?php wgs_analytics_head(); ?>
<link rel="icon" href="<?= portfolio_asset('assets/favicon.svg') ?>" type="image/svg+xml"><link rel="stylesheet" href="<?= portfolio_asset('assets/culture-lab.css') ?>"><script defer src="<?= portfolio_asset('assets/culture-lab.js') ?>"></script>
</head><body class="lab-body ninth-site world" data-lab-site="ninth">
<a class="lab-skip" href="#lab-main">Skip to content</a><div class="ninth-concept"><a href="/projects/ninth-form/">← Ninth Form case study</a><span>Independent fictional concept · demo checkout only</span></div>
<header class="ninth-nav"><a href="#top" class="ninth-wordmark">NINTH FORM</a><div class="mode-switch" aria-label="Choose experience mode"><button type="button" class="active" data-mode="world">World</button><button type="button" data-mode="shop">Shop</button></div><nav data-lab-menu aria-label="Ninth Form navigation"><a href="#collection">Collection</a><button type="button" data-show-shop>Shop all</button><a href="#process">Process</a><a href="#wholesale">Wholesale</a></nav><button class="bag-button" type="button" data-open-drawer="bag-drawer">Bag <span data-bag-count>0</span></button><button class="ninth-menu" type="button" data-menu-toggle aria-expanded="false">Menu</button></header>
<main id="lab-main">
<div data-world-view><section class="ninth-hero" id="top"><picture><source media="(max-width:600px)" srcset="/img/portfolio/ninth-form/cover-work-mobile-4x5.webp"><img src="/img/portfolio/ninth-form/case-hero-8x5.webp" alt="Ninth Form hero look in a pattern-paper studio" width="2880" height="1800" fetchpriority="high"></picture><div class="collection-mark"><p>Capsule 01 · 2026</p><h1>Cut to<br>change form.</h1><span>Limited-run modular clothing, designed as a fictional commerce concept.</span><button type="button" data-show-shop>Shop the capsule →</button></div><div class="look-index"><span>Look 01 / 06</span><button type="button" data-show-shop>Shop this look ↗</button></div></section>
<section class="ninth-statement" id="collection"><p>One look. More than one way to wear it.</p><h2>The outer coat, underlayer, side panel and fastening work together—or separately.</h2></section>
<section class="ninth-modular"><img src="/img/portfolio/ninth-form/world-01-modular-16x9.webp" alt="The Ninth Form look in a second modular configuration" width="2400" height="1350" loading="lazy"><div><span>Form 09 / Configuration 02</span><h2>Remove the side panel.<br>Reverse the balance.</h2><p>The same pieces, restyled without pretending a wardrobe needs to be disposable.</p><button type="button" data-show-shop>View the complete look →</button></div></section>
<section class="ninth-pieces"><div class="piece-copy"><span>Four pieces / one system</span><h2>What’s actually included.</h2><p>Product information separates the look into clear components, materials and availability—so the customer knows what they are buying.</p><button type="button" data-show-shop>Open product details →</button></div><img src="/img/portfolio/ninth-form/detail-01-components-square.webp" alt="Four separate components in the Ninth Form modular look" width="1600" height="1600" loading="lazy"></section></div>
<div data-shop-view hidden><section class="product-page" id="product"><div class="product-gallery"><img src="/img/portfolio/ninth-form/case-hero-8x5.webp" alt="Form 09 Modular Coat product view" width="2880" height="1800" data-product-image><div class="gallery-dots" aria-label="Product images"><button type="button" class="active" data-gallery-src="/img/portfolio/ninth-form/case-hero-8x5.webp" aria-label="View product image 1">01</button><button type="button" data-gallery-src="/img/portfolio/ninth-form/cover-work-mobile-4x5.webp" aria-label="View product image 2">02</button><button type="button" data-gallery-src="/img/portfolio/ninth-form/detail-02-construction-square.webp" aria-label="View product image 3">03</button><button type="button" data-gallery-src="/img/portfolio/ninth-form/detail-01-components-square.webp" aria-label="View product image 4">04</button></div></div><div class="product-info"><p>Capsule 01 · Look 01</p><h1>Form 09<br>Modular Coat</h1><div class="price"><span>$680 AUD</span><b>Demo product · ready-to-ship state</b></div><p class="product-plain">A sleeveless tailored outer layer with a detachable tobacco wool panel, bone wrap underlayer and adjustable blue webbing fastening.</p><div class="colour"><span>Colour</span><b>Ink / Tobacco / Bone</b></div><div class="size-head"><span>Select size</span><button type="button" data-open-drawer="fit-drawer">Size & fit guide</button></div><div class="sizes" aria-label="Choose a size"><?php foreach (['XS','S','M','L','XL'] as $size): ?><button type="button" data-size="<?= $size ?>"><?= $size ?></button><?php endforeach; ?></div><button class="add" type="button" data-add-bag>Choose a size</button><div class="product-notes"><details open><summary>Fit</summary><p>Close at the shoulder, adjustable through the waist and open through the lower body. Model is 178 cm and wears size S.</p></details><details><summary>Materials & construction</summary><p>Australian wool outer, textured cotton underlayer, tailoring canvas and brushed-steel hardware.</p></details><details><summary>Shipping & returns</summary><p>Demonstration copy: ships from Sydney in 2–3 business days with a 14-day unworn return state.</p></details></div></div></section><section class="product-detail"><img src="/img/portfolio/ninth-form/detail-02-construction-square.webp" alt="Close view of the Form 09 materials and fastening" width="1600" height="1600" loading="lazy"><div><span>Construction 01</span><h2>Nothing hidden behind “premium materials.”</h2><p>Matte wool. Textured cotton. A real tailoring canvas. Steel fittings that can be replaced rather than throwing out the garment.</p></div></section></div>
<section class="ninth-process" id="process"><div><span>Made in small runs</span><h2>Pattern first.<br>Image second.</h2><p>The collection begins at the cutting table. Full-size patterns, fit trials and modular attachment points are resolved before a campaign is photographed.</p></div><img src="/img/portfolio/ninth-form/world-02-workroom-16x9.webp" alt="Ninth Form pattern-cutting workroom" width="2400" height="1350" loading="lazy"></section>
<section class="ninth-wholesale" id="wholesale"><img src="/img/portfolio/ninth-form/wholesale-portrait-3x4.webp" alt="Ninth Form wholesale capsule and blank line sheet" width="1800" height="2400" loading="lazy"><div><span>For buyers, stylists and press</span><h2>The professional route is separate—and easy to find.</h2><p>Current collection notes, delivery windows, material details and approved campaign assets would live here.</p><button type="button" data-demo-status="Line-sheet requests are disabled in this concept">Preview the line-sheet route →</button><small>Concept only · no information is submitted</small></div></section>
</main><footer class="ninth-footer"><span>NINTH FORM</span><div><a href="/projects/ninth-form/">Read the WGS case study</a><a href="#wholesale">Customer care</a></div><p>Independent fictional concept by Web Girl Studio · demo store · 2026</p></footer><div class="lab-status" aria-live="polite" data-lab-status></div>
<div class="fit-drawer" id="fit-drawer" data-dialog data-drawer role="dialog" aria-modal="true" aria-labelledby="fit-title" hidden><button type="button" data-close-dialog>Close ×</button><p>Form 09 / Size & fit</p><h2 id="fit-title">Choose by garment measurements, not guesswork.</h2><div class="fit-summary"><b>Fit summary</b><p>Structured at the shoulder. Adjustable by 8 cm through the waist. Generous through the hip.</p></div><div class="measurements"><div><b>Size</b><span>XS</span><span>S</span><span>M</span><span>L</span><span>XL</span></div><div><b>Bust</b><span>82 cm</span><span>87 cm</span><span>92 cm</span><span>97 cm</span><span>102 cm</span></div><div><b>Waist</b><span>64 cm</span><span>69 cm</span><span>74 cm</span><span>79 cm</span><span>84 cm</span></div><div><b>Shoulder</b><span>38 cm</span><span>39 cm</span><span>40 cm</span><span>41 cm</span><span>42 cm</span></div></div><div class="measurement-cards"><?php foreach ([['XS','82','64','38'],['S','87','69','39'],['M','92','74','40'],['L','97','79','41'],['XL','102','84','42']] as [$s,$b,$w,$sh]): ?><dl><dt>Size <?= $s ?></dt><dd>Bust <b><?= $b ?> cm</b></dd><dd>Waist <b><?= $w ?> cm</b></dd><dd>Shoulder <b><?= $sh ?> cm</b></dd></dl><?php endforeach; ?></div><p class="fit-help">Between sizes? Choose by shoulder. The waist fastening is adjustable.</p></div>
<div class="bag-drawer" id="bag-drawer" data-dialog data-drawer role="dialog" aria-modal="true" aria-labelledby="bag-title" hidden><button type="button" data-close-dialog>Close ×</button><h2 id="bag-title">Your bag</h2><div data-empty-bag><p>Your bag is empty. The collection is small on purpose.</p></div><div class="bag-item" data-bag-item hidden><img src="/img/portfolio/ninth-form/detail-01-components-square.webp" alt="Form 09 Modular Coat" width="1600" height="1600"><div><b>Form 09 Modular Coat</b><span data-bag-variant>Ink / Tobacco / Bone</span><span>$680 AUD each</span><div class="bag-quantity"><button type="button" data-qty-minus aria-label="Decrease quantity">−</button><output data-qty>1</output><button type="button" data-qty-plus aria-label="Increase quantity">+</button></div></div></div><div class="bag-summary" data-bag-summary hidden><span>Subtotal</span><strong data-subtotal>$680 AUD</strong></div><button class="checkout" type="button" disabled data-checkout>Demo checkout</button><small>Demo only. No payment will be taken.</small></div>
</body></html>
